name: Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
    types: [opened, reopened, synchonize, ready_for_review]

jobs:
  pre_deployment:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
          
      - name: Lint w/ eslint & prettier
        run: npm run lint

      - name: Build
        run: npm run build:test

      - name: Unit tests
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress
          start: npm run start
          wait-on: http://localhost:8080
  deployment:
    if: github.event.name == 'push'
    needs: [pre_deployment]
    permissions: 
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with: 
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
